blank_issues_enabled: false
contact_links:
  - name: Others
    url: https://github.com/jiangtian616/JHenTai/discussions/new/choose
    about: | 
      其余问题请移步至讨论区 / Go to discussion for other questions
