name: Feature request
description: 提出一个功能建议 / Suggest an idea
labels:
  - "enhancement"
body:
  - type: markdown
    attributes:
      value: |
        提交功能请求前，请首先完成文末的自查步骤
        Please finish verify steps which list in the end first before Suggest an idea

  - type: textarea
    id: request
    attributes:
      label: 需求 / Requirement
      description: |
        在此处描述您的需求。这通常会是一个您想要的功能
        Ddescribe what you need here.
      placeholder: |
        我需要 XXX 功能 ...
        I want ABC feature ...
    validations:
      required: true

  - type: textarea
    id: impl
    attributes:
      label: 建议实现 / Suggested implemention
      description: |
        在此处表述您建议的实现方式。如有可能，UI 类功能请求还请尽量附上图示
        Describe your suggested implemention here, It's recommend to add a photo if you are making a UI feature request.
      placeholder: |
        建议在 XX 处添加 XX ...
        I recommend add ABC feature to DEF...
        图片（如果有）/ Photos (if exists)
    validations:
      required: true

  - type: textarea
    id: more
    attributes:
      label: 备注 / Addition details
      description: |
        在此处写下其他您想说的内容
        Describe addition details here
      placeholder: |
        其他有用的信息与附件
        Additional details and attachments
    validations:
      required: false

  - type: checkboxes
    id: check
    attributes:
      label: 自查步骤 / Verify steps
      description: |
        请确认您已经遵守所有必选项
        Please ensure you have obtained all needed options
      options:
        - label: 您已仔细查看并知情 [常见问题](https://github.com/jiangtian616/JHenTai/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98) 中的内容 / You have checked [Q&A](https://github.com/jiangtian616/JHenTai/wiki/Common-Qustions) carefully
          required: true
        - label: 您已搜索过 [Issue Tracker](https://github.com/jiangtian616/JHenTai/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/jiangtian616/JHenTai/issues), No duplicate or related open issue has been found
          required: true
        - label: 您确保这个 Issue 只提及一个问题。如果您有多个功能请求，烦请发起多个 Issue / Ensure there is only one feature request in this issue. Please make mutiply issue for mutiply bugs
          required: true
        - label: 您确保已使用最新版本测试，并且该问题在最新版本中仍未实现 / This feature have not supported in latest version
          required: true